name: Build, Push, and Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_REGION: ap-northeast-2  # 리전 환경 변수
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secrets에서 AWS 자격 증명 가져오기
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # GitHub Secrets에서 AWS 자격 증명 가져오기

      # 3. Build and Push Docker Image
      - name: Build and Push Docker Image
        env:
          ECR_REPOSITORY: 18_practice
          AWS_REGION: ap-northeast-2  # 서울 리전 예시
          IMAGE_TAG: latest
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  # GitHub Secrets에서 AWS_ACCOUNT_ID 가져오기
        run: |
          # 로그인 명령어에서 AWS_REGION을 사용하여 AWS CLI에 로그인
          $(aws ecr get-login-password --region $AWS_REGION) | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      # 4. Deploy to ECS
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: my-ecs-service
          cluster: my-ecs-cluster
          wait-for-service-stability: true
